### PR TITLE
Add `interlaced` option

### PR DESCRIPTION
**Pull request by luckyraul**
@sindresorhus create new PR

### CODE REVIEW

**Comment by sindresorhus** [comment]
> This needs to be documented. [,,] - https://github.com/imagemin/imagemin-optipng/pull/16#issuecomment-449869545

**Comment by sindresorhus** [comment]
I think you need to work more on the docs. Interlaced and progressive are not the same thing.

**Comment by luckyraul** [comment]
@sindresorhus Copy paste from https://imageoptim.com/help/prefs.html#optipng

**Comment by sindresorhus** [comment]
@luckyraul That doesn't matter. We have high standards for the docs.

**Comment by kevva** [comment]
@sindresorhus, I believe `interlaced` is just a flag for generating progressive images. I just think "progressive" is the general description of it.

**Comment by sindresorhus** [comment]
Interlaced is the opposite of progressive.

**Comment by kevva** [comment]
Every article and documentation I read is referring to progressive rendering when mentioning interlacing. I don't know for sure though. You can read about it on OptiPNG own documentation as well http://optipng.sourceforge.net/pngtech/optipng.html.

**Comment by luckyraul** [comment]
> Interlacing, useful for a faster, progressive rendering, is another component of the PNG image type that affects compression.
http://optipng.sourceforge.net/pngtech/optipng.html

**Comment by kevva** [comment]
From http://optipng.sourceforge.net/optipng-0.7.7.man.pdf:

> If the interlace type 0 is selected, the output image shall be non-interlaced (i.e. progressive-scanned). If the interlace type 1 is selected, the output image shall be interlaced using the Adam7
method. By default, the output shall have the same interlace type as the input.

To me that sounds like "progressive rendering" and "progressive scanned" is two different things.

**Comment by kevva** [comment]
@luckyraul, can you fix the merge conflicts?

**Comment by kevva** [comment]
Thanks, I will merge this tomorrow.

**Pull request merged**
