### PR TITLE
Option for interlacing the PNG file

### PR DESCRIPTION
**Pull request by jmnarloch**
Hi,

I would like to introduce this small PR to add option for PNG interlacing, by default this is going to be disabled, so this is going to be completely optional.

### CODE REVIEW

**Comment by jmnarloch** [comment]
May I ask you @shinnn @kevva to merge this?

**Comment by jmnarloch** [comment]
@shinnn @kevva any chance that this will get merged?

**Comment by sindresorhus** [comment]
From docs:

> −i type Select the interlace type (0−1).
If the interlace type 0 is selected, the output image shall be non-interlaced (i.e. progressivescanned).
If the interlace type 1 is selected, the output image shall be interlaced using the Adam7
method.

Seems it should be an option that supports: `progressive`, `interlace`, `auto` (default).

**Comment by sindresorhus** [comment]
@jmnarloch ?

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
